# Generated by Django 4.0.6 on 2022-07-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_email_index_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='Phoneno',
            new_name='PhoneNo',
        ),
    ]
