# Generated by Django 4.0.6 on 2022-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_phoneno_index_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Email', models.EmailField(default=0, max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='index',
        ),
    ]
