# Generated by Django 4.0.6 on 2022-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_indexdb_prime_delete_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdb',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
    ]
