# Generated by Django 4.0.6 on 2022-07-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_indexdb_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdb',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
