# Generated by Django 4.0.6 on 2022-07-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_indexdb_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexdb',
            old_name='mobile_number',
            new_name='Mobile_number',
        ),
    ]
