# Generated by Django 4.0.6 on 2022-07-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_mobile_number_indexdb_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prime',
        ),
    ]
