# Generated by Django 4.0.6 on 2022-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_prime'),
    ]

    operations = [
        migrations.CreateModel(
            name='primedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscription', models.CharField(choices=[(1, 'Subscribtion Mode by paying Rs.2500/- with Subscribtion mode you will get two entry passes for Tamil Fest 2022,Freshers Day 2022,Karthigai Deepam 2022 & Pongal Celebration 2023'), (2, 'Only for Tamil Fest 2022 (Rs.310/-per person.Which Includes entry to the cultural event,dinner and movie screening')], max_length=255)),
            ],
        ),
    ]
