# Generated by Django 4.0.6 on 2022-07-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_primedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscriptionfee', models.IntegerField()),
                ('contribution', models.IntegerField()),
                ('additionalpass', models.IntegerField()),
                ('Slot_Avaliability', models.IntegerField(blank=True, choices=[(1, '08:00 PM(40)'), (2, '08:30 PM(40)'), (3, '09:00 PM(20)'), (4, '09:30 PM(20)')])),
                ('payable', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='primedb',
            name='Subscription',
            field=models.IntegerField(blank=True, choices=[(1, 'Subscribtion Mode by paying Rs.2500/- with Subscribtion mode you will get two entry passes for Tamil Fest 2022,<break>Freshers Day 2022,Karthigai Deepam 2022 & Pongal Celebration 2023'), (2, 'Only for Tamil Fest 2022 (Rs.310/-per person.Which Includes entry to the cultural event,dinner and movie screening')]),
        ),
    ]
