# Generated by Django 4.0.6 on 2022-07-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_slot_avaliability_tbookdb_slot_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbookdb',
            name='Slot_time',
        ),
    ]
