# Generated by Django 4.0.6 on 2022-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_subscribdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonsubscribdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlyfeast_mode', models.IntegerField(null=0)),
            ],
        ),
    ]
