# Generated by Django 4.0.6 on 2022-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_rename_onlyfeast_mode_nonsubscribdb_onlyfeast_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbookdb',
        ),
        migrations.RemoveField(
            model_name='nonsubscribdb',
            name='onlyfeast',
        ),
        migrations.RemoveField(
            model_name='subscribdb',
            name='subscribtion',
        ),
        migrations.AddField(
            model_name='nonsubscribdb',
            name='Additionalpass',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (1, '2'), (1, '3'), (1, '4'), (1, '5')], default=0),
        ),
        migrations.AddField(
            model_name='nonsubscribdb',
            name='Contribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nonsubscribdb',
            name='Payable',
            field=models.IntegerField(default=310),
        ),
        migrations.AddField(
            model_name='nonsubscribdb',
            name='Slot_time',
            field=models.IntegerField(blank=True, choices=[(1, '08:00 PM(40)'), (2, '08:30 PM(40)'), (3, '09:00 PM(20)'), (4, '09:30 PM(20)')], default=0),
        ),
        migrations.AddField(
            model_name='nonsubscribdb',
            name='Subscriptionfee',
            field=models.IntegerField(default=310),
        ),
        migrations.AddField(
            model_name='subscribdb',
            name='Additionalpass',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (1, '2'), (1, '3'), (1, '4'), (1, '5')], default=0),
        ),
        migrations.AddField(
            model_name='subscribdb',
            name='Contribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscribdb',
            name='Payable',
            field=models.IntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='subscribdb',
            name='Slot_time',
            field=models.IntegerField(blank=True, choices=[(1, '08:00 PM(40)'), (2, '08:30 PM(40)'), (3, '09:00 PM(20)'), (4, '09:30 PM(20)')], default=0),
        ),
        migrations.AddField(
            model_name='subscribdb',
            name='Subscriptionfee',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='primedb',
            name='Subscription',
            field=models.IntegerField(blank=True, choices=[(1, 'Subscribtion Mode by paying Rs.2500/- with Subscribtion mode you will get two entry passes for Tamil Fest 2022,Freshers Day 2022,Karthigai Deepam 2022 & Pongal Celebration 2023'), (2, 'Only for Tamil Fest 2022 (Rs.310/-per person.Which Includes entry to the cultural event,dinner and movie screening')]),
        ),
    ]
