# Generated by Django 4.0.6 on 2022-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_delete_tbookdb_remove_nonsubscribdb_onlyfeast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdb',
            name='Mobile_number',
            field=models.IntegerField(blank=0, default=0),
        ),
        migrations.AlterField(
            model_name='primedb',
            name='Subscription',
            field=models.IntegerField(choices=[(1, 'Subscribtion '), (2, 'nonSubscription')], default='Select Choice'),
        ),
        migrations.AlterField(
            model_name='subscribdb',
            name='Contribution',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subscribdb',
            name='Payable',
            field=models.IntegerField(default=0),
        ),
    ]
