# Generated by Django 4.0.6 on 2022-08-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_indexdb_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribdb',
            name='Payable',
        ),
        migrations.AlterField(
            model_name='indexdb',
            name='Mobile_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='primedb',
            name='Subscription',
            field=models.IntegerField(choices=[(1, 'Subscription'), (2, 'nonSubscription')], default='Subscription'),
        ),
    ]
