# Generated by Django 4.0.6 on 2022-08-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_primedb_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primedb',
            name='Subscription',
            field=models.BooleanField(choices=[(1, 'Subscription'), (2, 'nonSubscription')], null=True),
        ),
    ]
