# Generated by Django 4.0.6 on 2022-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_primedb_subscription_alter_subscribdb_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primedb',
            name='Subscription',
            field=models.IntegerField(choices=[[1, 'Sub'], [2, 'nonSub']], default='Sub'),
        ),
    ]
